name: morpheus-graphql-examples-scotty
version: 0.1.0
github: "nalchevanidze/morpheus-graphql"
license: MIT
author: "Daviti Nalchevanidze"
category: web, graphql
synopsis: examples
copyright: "(c) 2019 Daviti Nalchevanidze"
description: examples of GraphQL APIs

dependencies:
  - base                            >= 4.7       && <  5
  - aeson                           >= 1.4.4.0
  - bytestring                      >= 0.10.4
  - text                            >= 1.2.3.0
  - containers                      >= 0.4.2.1
  - mtl                             >= 2.0
  - websockets                      >= 0.11.0
  - wai-websockets                  >= 1.0
  - morpheus-graphql
  - morpheus-graphql-core
  - morpheus-graphql-app
  - morpheus-graphql-subscriptions
  - scotty
  - warp
  - transformers
  - extra
  - http-types
  - stm

executables:
  scotty-server:
    main: Main.hs
    source-dirs: src
    ghc-options: -Wall
