name: morpheus-graphql-examples-servant
version: 0.1.0
github: "nalchevanidze/morpheus-graphql"
license: MIT
author: "Daviti Nalchevanidze"
category: web, graphql
synopsis: examples
copyright: "(c) 2019 Daviti Nalchevanidze"
description: examples of GraphQL APIs

dependencies:
  - base                              >= 4.7       && <  5
  - bytestring                        >= 0.10.4
  - text                              >= 1.2.3
  - mtl                               >= 2.0
  - morpheus-graphql
  - morpheus-graphql-subscriptions
  - wai-websockets                    >= 1.0
  - websockets                        >= 0.11.0
  - warp
  - servant-server
  - http-media
  - file-embed

executables:
  servant-server:
    main: Main.hs
    source-dirs: src
    ghc-options: -Wall
